cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
spring:
  application:
    name: booking-car
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/car_rental_system
    username: root
    password: 123456
logging:
  level:
    org.springframework.security: TRACE
server:
  port: 8080
  shutdown: graceful
  forward-headers-strategy: none
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days